version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: overlay-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: overlay_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: overlay-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=overlay_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/overlay_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Add phpMyAdmin for MySQL management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: overlay-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql

  # Add Mongo-Express for MongoDB management
  mongo-express:
    image: mongo-express
    container_name: overlay-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8082:8081"
    depends_on:
      - mongodb

volumes:
  mysql_data:
  mongodb_data: 
